/**
 * Combined Generator - Complete AI Prompt (Text + Code)
 *
 * Combines PromptGenerator and CodeGenerator into a single
 * ready-to-use prompt for AI
 */

import type { AnalysisResult, GeneratedPrompt } from '@shared/types/design-system.types';
import { PromptGenerator } from './prompt-generator';
import { CodeGenerator } from './code-generator';

export class CombinedGenerator {
  private promptGenerator: PromptGenerator;
  private codeGenerator: CodeGenerator;

  constructor() {
    this.promptGenerator = new PromptGenerator();
    this.codeGenerator = new CodeGenerator();
  }

  /**
   * Generate complete prompt (text + code)
   */
  generate(analysis: AnalysisResult): GeneratedPrompt {
    const description = this.promptGenerator.generate(analysis);
    const codeSnippets = this.codeGenerator.generate(analysis);

    return {
      description,
      codeSnippets,
      combined: this.combinePrompt(description, codeSnippets, analysis)
    };
  }

  /**
   * Combine description and code into single prompt
   */
  private combinePrompt(
    description: any,
    code: any,
    analysis: AnalysisResult
  ): string {
    let prompt = `# Design System Analysis\n\n`;
    prompt += `${description.overview}\n\n`;

    prompt += `---\n\n`;
    prompt += description.designSystem.colors;
    prompt += `\n`;
    prompt += description.designSystem.typography;
    prompt += `\n`;
    prompt += description.designSystem.spacing;
    prompt += `\n`;
    prompt += description.designSystem.components;
    prompt += `\n`;
    prompt += description.designSystem.interactions;

    if (description.patterns.length > 0) {
      prompt += `## Design Patterns Detected\n\n`;
      description.patterns.forEach((pattern: string) => {
        prompt += `- ${pattern}\n`;
      });
      prompt += `\n`;
    }

    prompt += `---\n\n`;

    prompt += `## CSS Variables (Design Tokens)\n\n`;
    prompt += `Copy and paste these into your CSS:\n\n`;
    prompt += `\`\`\`css\n${code.cssVariables}\`\`\`\n\n`;

    if (code.componentExamples.length > 0) {
      prompt += `## Component Examples\n\n`;

      for (const example of code.componentExamples.slice(0, 10)) {
        prompt += `### ${this.capitalize(example.type)}\n\n`;
        prompt += `HTML:\n\`\`\`html\n${example.html}\n\`\`\`\n\n`;
        prompt += `CSS:\n\`\`\`css\n${example.css}\n\`\`\`\n\n`;
      }
    }

    if (code.utilities) {
      prompt += `## Utility Classes\n\n`;
      prompt += `Optional utility classes based on the spacing and typography system:\n\n`;
      prompt += `\`\`\`css\n${code.utilities}\`\`\`\n\n`;
    }

    if (analysis.interactions.interactiveStates.length > 0 ||
        analysis.interactions.cssAnimations.transitions.length > 0) {
      prompt += `## 🎨 Practical Animation Examples\n\n`;
      prompt += `Ready-to-use CSS code for recreating the interactive effects:\n\n`;

      if (analysis.interactions.interactiveStates.length > 0) {
        const topState = analysis.interactions.interactiveStates[0];
        const hoverStyles = topState.states.hover;

        if (hoverStyles) {
          prompt += `### Hover Effect Example\n\n`;
          prompt += `\`\`\`css\n`;
          prompt += `/* Based on ${topState.selector} */\n`;
          prompt += `.interactive-element {\n`;

          const transition = analysis.interactions.cssAnimations.transitions[0];
          if (transition) {
            prompt += `  transition: ${transition.property} ${transition.duration} ${transition.timingFunction};\n`;
          }

          prompt += `}\n\n`;
          prompt += `.interactive-element:hover {\n`;

          Object.entries(hoverStyles).slice(0, 4).forEach(([prop, val]) => {
            prompt += `  ${prop}: ${val};\n`;
          });

          prompt += `}\n`;
          prompt += `\`\`\`\n\n`;
        }
      }

      if (analysis.interactions.cssAnimations.keyframeAnimations.length > 0) {
        const anim = analysis.interactions.cssAnimations.keyframeAnimations[0];
        prompt += `### Animation Example\n\n`;
        prompt += `\`\`\`css\n`;
        prompt += `/* ${anim.name} animation */\n`;
        prompt += `.animated-element {\n`;
        prompt += `  animation: ${anim.name} ${anim.duration || '1s'} ${anim.timingFunction || 'ease'} ${anim.iterationCount || 'infinite'};\n`;
        prompt += `}\n\n`;
        prompt += `/* Copy the @keyframes from the site's CSS */\n`;
        prompt += `\`\`\`\n\n`;
      }
    }

    prompt += `---\n\n`;
    prompt += `**Generated by DesignMirror**\n`;
    prompt += `Source: ${analysis.url}\n`;
    prompt += `Date: ${new Date(analysis.timestamp).toLocaleString()}\n`;
    prompt += `Elements analyzed: ${analysis.elementCount}\n\n`;

    prompt += `## How to use this prompt\n\n`;
    prompt += `1. Copy the CSS Variables section and add to your :root selector\n`;
    prompt += `2. Reference the component examples to recreate similar UI elements\n`;
    prompt += `3. Use the spacing and typography scales for consistency\n`;
    prompt += `4. Apply the color palette to maintain the visual identity\n\n`;

    prompt += `Ask me to help you implement any of these design tokens or components!\n`;

    return prompt;
  }

  /**
   * Capitalize string
   */
  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

export default CombinedGenerator;
