# GitHub Sponsors configuration
# Uncomment and update with your info when ready

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://buymeacoffee.com/yourusername"]
